### ISSUE TITLE
Error script

### ISSUE THREAD

**Issue by MakuSensei** [arcolinuxb/arco-plasma#1]
makusensei@loli-linux ~/Descargas/arco-plasma/installation-scripts   [18:57:58] 
> $ sh ./30-build-the-iso-local-v1.sh                          [±master ●]

################################################################## 
Phase 1 : clean up and download the latest ArcoLinux-iso from github
################################################################## 

Deleting the work folder if one exists
Deleting the build folder if one exists - takes some time
Git cloning files and folder to work folder
Clonando en '../work'...
remote: Counting objects: 782, done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 782 (delta 110), reused 114 (delta 58), pack-reused 607
Recibiendo objetos: 100% (782/782), 4.04 MiB | 2.54 MiB/s, listo.
Resolviendo deltas: 100% (444/444), listo.

################################################################## 
Phase 2 : Getting the latest versions for some important files
################################################################## 

Removing the old packages.both file from work folder
Copying the new packages.both file
Removing old files/folders from /etc/skel
getting .bashrc from arcolinux-root
--2018-06-12 19:01:18--  https://raw.githubusercontent.com/arcolinux/arcolinux-root/master/root/.bashrc-latest
Cargado certificado CA '/etc/ssl/certs/ca-certificates.crt'
Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.216.133
Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[151.101.216.133]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 1976 (1,9K) [text/plain]
Grabando a: “../work/archiso/airootfs/etc/skel/.bashrc”

../work/archiso/air 100%[===================>]   1,93K  --.-KB/s    en 0s      

2018-06-12 19:01:18 (25,0 MB/s) - “../work/archiso/airootfs/etc/skel/.bashrc” guardado [1976/1976]

################################################################## 
Phase 3 : Renaming the iso to BYOI and the desktop
################################################################## 

Renaming to ArcoLinuxB-plasma

################################################################## 
Phase 4 : Let us build the iso
################################################################## 

Checking if archiso is installed
################################################################
################################################################
Copying files and folder to ~/arcolinuxb-build as root
################################################################
In order to build an iso we need to clean your cache (y/n)?y
Paquetes a mantener:
  Todos los paquetes instalados localmente

Directorio de la caché: /var/cache/pacman/pkg/
:: ¿Desea quitar los paquetes restantes de la caché? [S/n] s
quitando paquetes antiguos de la caché...

Directorio de la base de datos: /var/lib/pacman/
:: ¿Desea quitar los repositorios no utilizados? [S/n] s
quitando repositorios de sincronización no utilizados...
Making the Iso
==> ERROR: El archivo de depósito /usr/share/pacman/keyrings/arcolinux.gpg no existe.

[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   init
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work/x86_64
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:        Pacman config file:   work/pacman.conf

[mkarchiso] INFO: Installing packages to 'work/x86_64/airootfs/'...
==> Creating install root at work/x86_64/airootfs
==> Installing packages to work/x86_64/airootfs
warning: option --root is deprecated; use --sysroot instead
:: Synchronizing package databases...
 core                     129.8 KiB   245K/s 00:01 [----------------------] 100%
 extra                   1639.9 KiB  1481K/s 00:01 [----------------------] 100%
 community                  4.4 MiB   757K/s 00:06 [----------------------] 100%
 multilib                 170.1 KiB   183K/s 00:01 [----------------------] 100%
 arcolinux_repo            20.6 KiB   129K/s 00:00 [----------------------] 100%
 arcolinux_repo.sig       310.0   B  0.00B/s 00:00 [----------------------] 100%
error: arcolinux_repo: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
error: failed to update arcolinux_repo (invalid or corrupted database (PGP signature))
 arcolinux_repo_iso        46.9 KiB   293K/s 00:00 [----------------------] 100%
 arcolinux_repo_iso.sig   310.0   B  0.00B/s 00:00 [----------------------] 100%
error: arcolinux_repo_iso: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
error: failed to update arcolinux_repo_iso (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
==> ERROR: Failed to install packages to new root
                                                                                
makusensei@loli-linux ~/Descargas/arco-plasma/installation-scripts   [19:01:41] 
> $

**Comment by arcolinuxz** [comment]
just wait a few minutes
It means I just updated the github.
A lot of pushes committed yesterday.

**Comment by MakuSensei** [comment]
Hi, I have a query.
to install archlinux I have a problem with my wifi adapter "tp-link"

Currently to install this distro, I have to resort to Antergos (iso GUI of archlinux), and manually compile the driver.

To do this, I use my cell phone as a USB modem to install the git, dkms and linux-headers packages.

My query is on how I can include these packages "git, dkms and linux-headers." in a live iso of archlinux to facilitate the installation?

**Comment by arcolinuxz** [comment]
Sounds like you are a candidate to learn, use and test the ArcoLinuxB
project.

There you make the iso yourself and change the packages. Only Aur packages
are not yet included.

Cheers
Erik
