### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by HardcodeCoder** [arcolinuxb/arco-plasma#2]
I just have a small suggestions as to how to group packages in the `packages.x86_64` list.
Instead of grouping packages under different categories as to where it belongs. It can be categorised as:

1. Display managers
2. Base packages for plasma DE ('plasma-desktop' group of arch)
3. Extra packages for plasma (everythingthat's under 'plasma' group but not in 'plasma-desktop'). 
4. KDE applications most common/useful
3. KDE application others.
4. Applications (Categorised as Browsers, utilities, Multimedia, torrent, editors and so on).
5. Fonts can be grouped together
6. Themes can be grouped together.
7. Anything else can also be grouped based on categories.

After the essentials, all other packages can be included as groups or categories with or without the source of origin.

I feel like providing a small description of each section really helps in package selection and one might not be fully aware of what each package/group of packages does and whether or not it's optional or necessary for certain kind of functionality.

This is just an idea. I might be wrong here and the reason you decide to put them that way may have some other reasons which I am happy to learn about.

Edit: Categories for kernels can also be included.

**Comment by arcolinuxz** [comment]
We do not write a list per desktop
We write the same packages file over 20+ desktops
You are free to change it.
We compare meld between desktops.
Every package is on the same line on all desktops making scripting easier.
Changing the name, deleting it, adding it becomes super easy over 20+ desktops

**Comment by HardcodeCoder** [comment]
Yes. I got your point. Thanks for the explanation.
